import { Demand, TeamMemberLiveStatus, AlertItem, DailyLedger, LeaderboardEntry, UserProfile, UserAccount } from './types';

export const IMAGE_URLS = {
  brandLogo: 'https://lh3.googleusercontent.com/aida/AEtjO1WCo5RYz2FNZYut99U7fOy8PJW0D7ZpRgkhLJNKYD1tshnbHphSPfjW_pYax98uG2uRGtZZpmCFCIyqYj_o7m2JMqC0whiC0gF7GZHx18dvInp3pjMd_h8mertQIJNtEgqTjTAuzGCzMwSrboMIwRzpFsBioB_AJxoRNbNPhJ4lrIeZEsWdEAH0C6XqSkBiL9fRwOk1_xQ4a0C2mcdDWCHKXQEo9m3m3IAEnu5fg1eRZIaTHA-thv5Y_Q',
  carlosEduardo: '',
  carlosEduardoPortrait: '',
  beatrizLimaHeadshot: '',
  beatrizLimaFinance: '',
  beatrizLimaThumb: '',
  marianaRios: '',
  felipeSantos: '',
  marcosSouza1: '',
  marcosSouza2: '',
  julianaPrado: '',
  lucasMendes: '',
};

export const PROFILES: Record<'gestor' | 'colaborador', UserProfile> = {
  gestor: {
    id: 'carlos-eduardo',
    name: 'Carlos Eduardo',
    email: 'carlos@conecta.com',
    personalNumber: '1001',
    roleTitle: 'Gestor Geral de Operações',
    department: 'Gestão de Pessoas (RH)',
    avatar: '',
    role: 'gestor',
    initials: 'CE',
    companyName: 'Matriz Operacional',
  },
  colaborador: {
    id: 'beatriz-lima',
    name: 'Beatriz Lima',
    personalNumber: '1002',
    email: 'beatriz@conecta.com',
    roleTitle: 'Analista Financeira Pleno',
    department: 'Financeiro',
    avatar: '',
    role: 'colaborador',
    initials: 'BL',
    companyName: 'Matriz Operacional',
  },
};

// Contas de Usuários Registradas no Sistema (Login 4 dígitos + PIN 4 dígitos)
export const INITIAL_ACCOUNTS: UserAccount[] = [
  {
    id: 'carlos-eduardo',
    name: 'Carlos Eduardo',
    email: 'carlos@conecta.com',
    personalNumber: '1001',
    password: '1234',
    roleTitle: 'Gestor Geral',
    department: 'Gestão de Pessoas (RH)',
    avatar: '',
    role: 'gestor',
    initials: 'CE',
    companyName: 'Matriz Operacional',
    createdAt: '01/01/2026',
    lastLogin: 'Hoje, 08:30',
    status: 'ativo',
  },
  {
    id: 'beatriz-lima',
    name: 'Beatriz Lima',
    personalNumber: '1002',
    email: 'beatriz@conecta.com',
    password: '1234',
    roleTitle: 'Analista Financeira',
    department: 'Financeiro',
    avatar: '',
    role: 'colaborador',
    initials: 'BL',
    companyName: 'Matriz Operacional',
    createdAt: '15/01/2026',
    lastLogin: 'Hoje, 09:02',
    status: 'ativo',
  },
  {
    id: 'rodrigo-mendes',
    name: 'Rodrigo Mendes',
    personalNumber: '1003',
    email: 'rodrigo@conecta.com',
    password: '1234',
    roleTitle: 'Coordenador de Logística',
    department: 'Logística',
    avatar: '',
    role: 'colaborador',
    initials: 'RM',
    companyName: 'Matriz Operacional',
    createdAt: '10/02/2026',
    lastLogin: 'Ontem, 18:00',
    status: 'ativo',
  },
  {
    id: 'mariana-santos',
    name: 'Mariana Santos',
    personalNumber: '1004',
    email: 'mariana@conecta.com',
    password: '1234',
    roleTitle: 'Executiva de Vendas & Growth',
    department: 'Marketing e Vendas',
    avatar: '',
    role: 'colaborador',
    initials: 'MS',
    companyName: 'Matriz Operacional',
    createdAt: '20/02/2026',
    lastLogin: 'Hoje, 08:45',
    status: 'ativo',
  },
  {
    id: 'juliana-prado',
    name: 'Juliana Prado',
    personalNumber: '1005',
    email: 'juliana@conecta.com',
    password: '1234',
    roleTitle: 'Analista de Gestão de Pessoas',
    department: 'Gestão de Pessoas (RH)',
    avatar: '',
    role: 'colaborador',
    initials: 'JP',
    companyName: 'Matriz Operacional',
    createdAt: '25/02/2026',
    lastLogin: 'Hoje, 09:15',
    status: 'ativo',
  },
];

// ZERADO: Inicia totalmente sem demandas ativas
export const INITIAL_DEMANDS: Demand[] = [];

// ZERADO: Inicia totalmente sem alertas ativos
export const INITIAL_ALERTS: AlertItem[] = [];

// ZERADO: Tarefa ativa inicial do colaborador começa nula ou vazia
export const EMPLOYEE_HERO_TASK: Demand | null = null;

// Equipe em estado zero / aguardando demandas
export const TEAM_MEMBERS: TeamMemberLiveStatus[] = [
  {
    id: 'm1',
    name: 'Beatriz Lima',
    personalNumber: '1002',
    department: 'Financeiro',
    avatar: '',
    initials: 'BL',
    tasksCount: 0,
    status: 'online',
    statusText: 'Disponível',
    punchStatus: 'Ausente',
    punchTime: '--:--',
  },
  {
    id: 'm2',
    name: 'Rodrigo Mendes',
    personalNumber: '1003',
    department: 'Logística',
    avatar: '',
    initials: 'RM',
    tasksCount: 0,
    status: 'online',
    statusText: 'Disponível',
    punchStatus: 'Ausente',
    punchTime: '--:--',
  },
  {
    id: 'm3',
    name: 'Mariana Santos',
    personalNumber: '1004',
    department: 'Marketing e Vendas',
    avatar: '',
    initials: 'MS',
    tasksCount: 0,
    status: 'online',
    statusText: 'Disponível',
    punchStatus: 'Ausente',
    punchTime: '--:--',
  },
  {
    id: 'm4',
    name: 'Juliana Prado',
    personalNumber: '1005',
    department: 'Gestão de Pessoas (RH)',
    avatar: '',
    initials: 'JP',
    tasksCount: 0,
    status: 'online',
    statusText: 'Disponível',
    punchStatus: 'Ausente',
    punchTime: '--:--',
  },
];

// ZERADO: Espelho semanal de ponto zerado (sem marcações ainda)
export const WEEKLY_LEDGER: DailyLedger[] = [
  {
    dayName: 'Segunda',
    dateStr: '21/10',
    punch1: '--:--',
    punch2: '--:--',
    punch3: '--:--',
    punch4: '--:--',
    hoursWorked: '0h 00min',
    balance: '0h 00min',
  },
  {
    dayName: 'Terça',
    dateStr: '22/10',
    punch1: '--:--',
    punch2: '--:--',
    punch3: '--:--',
    punch4: '--:--',
    hoursWorked: '0h 00min',
    balance: '0h 00min',
  },
  {
    dayName: 'Quarta',
    dateStr: '23/10',
    punch1: '--:--',
    punch2: '--:--',
    punch3: '--:--',
    punch4: '--:--',
    hoursWorked: '0h 00min',
    balance: '0h 00min',
  },
  {
    dayName: 'Quinta',
    dateStr: '24/10',
    punch1: '--:--',
    punch2: '--:--',
    punch3: '--:--',
    punch4: '--:--',
    hoursWorked: '0h 00min',
    balance: 'Aguardando 1º registro',
    isToday: true,
  },
  {
    dayName: 'Sexta',
    dateStr: '25/10',
    punch1: '--:--',
    punch2: '--:--',
    punch3: '--:--',
    punch4: '--:--',
    hoursWorked: '0h 00min',
    balance: '0h 00min',
    isFuture: true,
  },
];

// Ranking inicial zerado / neutro
export const LEADERBOARD: LeaderboardEntry[] = [
  {
    position: 1,
    name: 'Colaborador em Destaque',
    role: 'Especialista',
    department: 'Setor Financeiro & BI',
    isAnonymized: true,
    anonymousId: '#012',
    statusBadge: 'Início de Ciclo',
    statusTrend: 'stable',
    relativeStatus: 'Aguardando Entregas',
  },
  {
    position: 2,
    name: 'Destaque do Mês',
    role: 'Analista Sênior',
    department: 'Setor Operações SP',
    isAnonymized: true,
    anonymousId: '#041',
    statusBadge: 'Início de Ciclo',
    statusTrend: 'stable',
    relativeStatus: 'Aguardando Entregas',
  },
  {
    position: 3,
    name: 'Beatriz Lima (Você)',
    role: 'Analista Financeira Pleno',
    department: 'Financeiro & Controladoria',
    avatar: IMAGE_URLS.beatrizLimaThumb,
    initials: 'BL',
    isCurrentUser: true,
    statusBadge: 'Suas Métricas',
    statusTrend: 'stable',
    slaScore: '0% de Eficácia',
    relativeStatus: 'Iniciando Ciclo',
  },
  {
    position: 4,
    name: 'Colaborador #084',
    role: 'Analista',
    department: 'Operações',
    isAnonymized: true,
    anonymousId: '#084',
    relativeStatus: 'Estável',
    statusTrend: 'stable',
  },
  {
    position: 5,
    name: 'Colaborador #112',
    role: 'Assistente',
    department: 'Suporte',
    isAnonymized: true,
    anonymousId: '#112',
    relativeStatus: 'Estável',
    statusTrend: 'stable',
  },
  {
    position: 6,
    name: 'Colaborador #019',
    role: 'Consultor',
    department: 'Comercial',
    isAnonymized: true,
    anonymousId: '#019',
    relativeStatus: 'Estável',
    statusTrend: 'stable',
  },
  {
    position: 7,
    name: 'Colaborador #203',
    role: 'Analista',
    department: 'TI & Infra',
    isAnonymized: true,
    anonymousId: '#203',
    relativeStatus: 'Estável',
    statusTrend: 'stable',
  },
];

// Dados de Exemplo para restauração se o usuário desejar preencher a qualquer momento
export const SAMPLE_DEMANDS: Demand[] = [
  {
    id: 'REQ-8492',
    protocol: '#REQ-8492',
    title: 'Fechamento Fiscal - Conciliação Bancária',
    description: 'Conciliação e conferência de todas as movimentações fiscais da conta corporativa, identificação de divergências e lançamento contábil.',
    department: 'Financeiro',
    assigneeName: 'Beatriz Lima',
    assigneeRole: 'Analista Financeira Pleno',
    assigneeAvatar: '',
    assigneeInitials: 'BL',
    requesterName: 'Carlos Eduardo',
    requesterRole: 'Gestor Geral',
    requesterAvatar: '',
    priority: 'Urgente',
    status: 'Atrasada',
    progressPercent: 45,
    deadlineDisplay: 'Hoje, 14:00',
    deadlineRelative: 'Atrasado (3h)',
    createdAtRelative: 'Criado há 2d',
    slaBreach: true,
  },
  {
    id: 'REQ-8490',
    protocol: '#REQ-8490',
    title: 'Roteirização e Despacho de Cargas - Rota Sudeste',
    description: 'Mapeamento de rotas de rastreamento e homologação de remessas com a frota logística contratada.',
    department: 'Logística',
    assigneeName: 'Rodrigo Mendes',
    assigneeRole: 'Coordenador de Logística',
    assigneeAvatar: '',
    assigneeInitials: 'RM',
    requesterName: 'Carlos Eduardo',
    requesterRole: 'Gestor Geral',
    requesterAvatar: '',
    priority: 'Alta',
    status: 'Em Andamento',
    progressPercent: 60,
    deadlineDisplay: 'Hoje, 18:30',
    deadlineRelative: 'Faltam 4h',
    createdAtRelative: 'Criado hoje',
  },
  {
    id: 'REQ-8488',
    protocol: '#REQ-8488',
    title: 'Campanha de Prospecção Q4 - Segmento B2B',
    description: 'Ativação de régua de e-mails e contatos comerciais para novos leads qualificados de vendas corporativas.',
    department: 'Marketing e Vendas',
    assigneeName: 'Mariana Santos',
    assigneeRole: 'Executiva de Vendas & Growth',
    assigneeAvatar: '',
    assigneeInitials: 'MS',
    requesterName: 'Carlos Eduardo',
    requesterRole: 'Gestor Geral',
    requesterAvatar: '',
    priority: 'Média',
    status: 'Pendente',
    progressPercent: 20,
    deadlineDisplay: 'Amanhã, 12:00',
    deadlineRelative: 'Aprovação Pendente',
    createdAtRelative: 'Aguarda você',
  },
  {
    id: 'REQ-8902',
    protocol: '#REQ-8902',
    title: 'Admissão e Onboarding de Novos Talentos',
    description: 'Validação documental, preparação de crachás, integração de novos membros e recolhimento de termos trabalhistas.',
    department: 'Gestão de Pessoas (RH)',
    assigneeName: 'Juliana Prado',
    assigneeRole: 'Analista de Gestão de Pessoas',
    assigneeAvatar: '',
    assigneeInitials: 'JP',
    requesterName: 'Carlos Eduardo',
    requesterRole: 'Gestor Geral',
    requesterAvatar: '',
    priority: 'Urgente',
    status: 'Atrasada',
    progressPercent: 40,
    deadlineDisplay: 'Ontem às 18:00',
    deadlineRelative: '+14h de excedência',
    createdAtRelative: 'Criado há 3d',
    slaBreach: true,
  },
];
